### ISSUE TITLE
如果clash上面有多家机场的多个订阅，parser该怎么写？

### ISSUE THREAD

**Issue by Nevidebla** [lwd-temp/anti-ip-attribution#36]
按照给的模板文件，只能写一个订阅。
如果有多个订阅的话，就按照同样的缩进格式，在后面挨个复制粘贴一遍？
![image](https://user-images.githubusercontent.com/54260027/223892105-2c92b79c-835a-49f0-8fec-c2848da10c22.png)

**Comment by lwd-temp** [comment]
这是CFW的使用问题，参见 https://docs.cfw.lbyczf.com/contents/parser.html#%E6%AD%A3%E5%88%99%E5%8C%B9%E9%85%8D

以下配置应该会匹配任意HTTP协议链接，注意将`url`替换为`reg`。
```
parsers:
  - reg: ^http.+$
    yaml:
      后文省略
```
